// Code generated by mockery. DO NOT EDIT.

package mocker

import (
	context "context"

	logger "github.com/shandysiswandi/gostarter/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: ctx, message, fields
func (_m *MockLogger) Debug(ctx context.Context, message string, fields ...logger.Field) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) Debug(ctx interface{}, message interface{}, fields ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{ctx, message}, fields...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(ctx context.Context, message string, fields ...logger.Field)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]logger.Field, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(logger.Field)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(context.Context, string, ...logger.Field)) *MockLogger_Debug_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: ctx, message, err, fields
func (_m *MockLogger) Error(ctx context.Context, message string, err error, fields ...logger.Field) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, message, err)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - err error
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) Error(ctx interface{}, message interface{}, err interface{}, fields ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, message, err}, fields...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(ctx context.Context, message string, err error, fields ...logger.Field)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]logger.Field, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(logger.Field)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(context.Context, string, error, ...logger.Field)) *MockLogger_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: ctx, message, fields
func (_m *MockLogger) Info(ctx context.Context, message string, fields ...logger.Field) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) Info(ctx interface{}, message interface{}, fields ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, message}, fields...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(ctx context.Context, message string, fields ...logger.Field)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]logger.Field, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(logger.Field)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(context.Context, string, ...logger.Field)) *MockLogger_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Warn provides a mock function with given fields: ctx, message, fields
func (_m *MockLogger) Warn(ctx context.Context, message string, fields ...logger.Field) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) Warn(ctx interface{}, message interface{}, fields ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{ctx, message}, fields...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(ctx context.Context, message string, fields ...logger.Field)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]logger.Field, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(logger.Field)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(context.Context, string, ...logger.Field)) *MockLogger_Warn_Call {
	_c.Call.Return(run)
	return _c
}

// WithFields provides a mock function with given fields: fields
func (_m *MockLogger) WithFields(fields ...logger.Field) logger.Logger {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithFields")
	}

	var r0 logger.Logger
	if rf, ok := ret.Get(0).(func(...logger.Field) logger.Logger); ok {
		r0 = rf(fields...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}

	return r0
}

// MockLogger_WithFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithFields'
type MockLogger_WithFields_Call struct {
	*mock.Call
}

// WithFields is a helper method to define mock.On call
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) WithFields(fields ...interface{}) *MockLogger_WithFields_Call {
	return &MockLogger_WithFields_Call{Call: _e.mock.On("WithFields",
		append([]interface{}{}, fields...)...)}
}

func (_c *MockLogger_WithFields_Call) Run(run func(fields ...logger.Field)) *MockLogger_WithFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]logger.Field, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(logger.Field)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_WithFields_Call) Return(_a0 logger.Logger) *MockLogger_WithFields_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogger_WithFields_Call) RunAndReturn(run func(...logger.Field) logger.Logger) *MockLogger_WithFields_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
