// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/region/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSearch is an autogenerated mock type for the Search type
type MockSearch struct {
	mock.Mock
}

type MockSearch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearch) EXPECT() *MockSearch_Expecter {
	return &MockSearch_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockSearch) Call(ctx context.Context, in domain.SearchInput) ([]domain.Region, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 []domain.Region
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SearchInput) ([]domain.Region, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SearchInput) []domain.Region); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Region)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SearchInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearch_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockSearch_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.SearchInput
func (_e *MockSearch_Expecter) Call(ctx interface{}, in interface{}) *MockSearch_Call_Call {
	return &MockSearch_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockSearch_Call_Call) Run(run func(ctx context.Context, in domain.SearchInput)) *MockSearch_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SearchInput))
	})
	return _c
}

func (_c *MockSearch_Call_Call) Return(_a0 []domain.Region, _a1 error) *MockSearch_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearch_Call_Call) RunAndReturn(run func(context.Context, domain.SearchInput) ([]domain.Region, error)) *MockSearch_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearch creates a new instance of MockSearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearch {
	mock := &MockSearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
