// Code generated by mockery. DO NOT EDIT.

package pkgmock

import mock "github.com/stretchr/testify/mock"

// MockStatusCoder is an autogenerated mock type for the StatusCoder type
type MockStatusCoder struct {
	mock.Mock
}

type MockStatusCoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusCoder) EXPECT() *MockStatusCoder_Expecter {
	return &MockStatusCoder_Expecter{mock: &_m.Mock}
}

// StatusCode provides a mock function with given fields:
func (_m *MockStatusCoder) StatusCode() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusCode")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockStatusCoder_StatusCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusCode'
type MockStatusCoder_StatusCode_Call struct {
	*mock.Call
}

// StatusCode is a helper method to define mock.On call
func (_e *MockStatusCoder_Expecter) StatusCode() *MockStatusCoder_StatusCode_Call {
	return &MockStatusCoder_StatusCode_Call{Call: _e.mock.On("StatusCode")}
}

func (_c *MockStatusCoder_StatusCode_Call) Run(run func()) *MockStatusCoder_StatusCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatusCoder_StatusCode_Call) Return(_a0 int) *MockStatusCoder_StatusCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatusCoder_StatusCode_Call) RunAndReturn(run func() int) *MockStatusCoder_StatusCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatusCoder creates a new instance of MockStatusCoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusCoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusCoder {
	mock := &MockStatusCoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
