// Code generated by mockery. DO NOT EDIT.

package pkgmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockQueryer is an autogenerated mock type for the Queryer type
type MockQueryer struct {
	mock.Mock
}

type MockQueryer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryer) EXPECT() *MockQueryer_Expecter {
	return &MockQueryer_Expecter{mock: &_m.Mock}
}

// QueryContext provides a mock function with given fields: ctx, _a1, args
func (_m *MockQueryer) QueryContext(ctx context.Context, _a1 string, args ...interface{}) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (*sql.Rows, error)); ok {
		return rf(ctx, _a1, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Rows); ok {
		r0 = rf(ctx, _a1, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, _a1, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueryer_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockQueryer_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - args ...interface{}
func (_e *MockQueryer_Expecter) QueryContext(ctx interface{}, _a1 interface{}, args ...interface{}) *MockQueryer_QueryContext_Call {
	return &MockQueryer_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, _a1}, args...)...)}
}

func (_c *MockQueryer_QueryContext_Call) Run(run func(ctx context.Context, _a1 string, args ...interface{})) *MockQueryer_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockQueryer_QueryContext_Call) Return(_a0 *sql.Rows, _a1 error) *MockQueryer_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueryer_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (*sql.Rows, error)) *MockQueryer_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, query, args
func (_m *MockQueryer) QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// MockQueryer_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type MockQueryer_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *MockQueryer_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *MockQueryer_QueryRowContext_Call {
	return &MockQueryer_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockQueryer_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *MockQueryer_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockQueryer_QueryRowContext_Call) Return(_a0 *sql.Row) *MockQueryer_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueryer_QueryRowContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) *sql.Row) *MockQueryer_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryer creates a new instance of MockQueryer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryer {
	mock := &MockQueryer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
