// Code generated by mockery. DO NOT EDIT.

package pkgmock

import (
	http "github.com/shandysiswandi/gostarter/pkg/http"
	mock "github.com/stretchr/testify/mock"
)

// MockServeOptionFunc is an autogenerated mock type for the ServeOptionFunc type
type MockServeOptionFunc struct {
	mock.Mock
}

type MockServeOptionFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServeOptionFunc) EXPECT() *MockServeOptionFunc_Expecter {
	return &MockServeOptionFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockServeOptionFunc) Execute(_a0 *http.Serve) {
	_m.Called(_a0)
}

// MockServeOptionFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockServeOptionFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *http.Serve
func (_e *MockServeOptionFunc_Expecter) Execute(_a0 interface{}) *MockServeOptionFunc_Execute_Call {
	return &MockServeOptionFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockServeOptionFunc_Execute_Call) Run(run func(_a0 *http.Serve)) *MockServeOptionFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Serve))
	})
	return _c
}

func (_c *MockServeOptionFunc_Execute_Call) Return() *MockServeOptionFunc_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServeOptionFunc_Execute_Call) RunAndReturn(run func(*http.Serve)) *MockServeOptionFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServeOptionFunc creates a new instance of MockServeOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServeOptionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServeOptionFunc {
	mock := &MockServeOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
