// Code generated by mockery. DO NOT EDIT.

package pkgmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockExecer is an autogenerated mock type for the Execer type
type MockExecer struct {
	mock.Mock
}

type MockExecer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecer) EXPECT() *MockExecer_Expecter {
	return &MockExecer_Expecter{mock: &_m.Mock}
}

// ExecContext provides a mock function with given fields: ctx, _a1, args
func (_m *MockExecer) ExecContext(ctx context.Context, _a1 string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (sql.Result, error)); ok {
		return rf(ctx, _a1, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, _a1, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, _a1, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecer_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockExecer_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - args ...interface{}
func (_e *MockExecer_Expecter) ExecContext(ctx interface{}, _a1 interface{}, args ...interface{}) *MockExecer_ExecContext_Call {
	return &MockExecer_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, _a1}, args...)...)}
}

func (_c *MockExecer_ExecContext_Call) Run(run func(ctx context.Context, _a1 string, args ...interface{})) *MockExecer_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockExecer_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *MockExecer_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecer_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (sql.Result, error)) *MockExecer_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecer creates a new instance of MockExecer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecer {
	mock := &MockExecer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
