// Code generated by mockery. DO NOT EDIT.

package pkgmock

import mock "github.com/stretchr/testify/mock"

// MockString is an autogenerated mock type for the String type
type MockString struct {
	mock.Mock
}

type MockString_Expecter struct {
	mock *mock.Mock
}

func (_m *MockString) EXPECT() *MockString_Expecter {
	return &MockString_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields:
func (_m *MockString) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockString_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockString_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockString_Expecter) Generate() *MockString_Generate_Call {
	return &MockString_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockString_Generate_Call) Run(run func()) *MockString_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockString_Generate_Call) Return(_a0 string) *MockString_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockString_Generate_Call) RunAndReturn(run func() string) *MockString_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockString creates a new instance of MockString. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockString(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockString {
	mock := &MockString{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
