// Code generated by mockery. DO NOT EDIT.

package pkgmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSubscriberHandlerFunc is an autogenerated mock type for the SubscriberHandlerFunc type
type MockSubscriberHandlerFunc struct {
	mock.Mock
}

type MockSubscriberHandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriberHandlerFunc) EXPECT() *MockSubscriberHandlerFunc_Expecter {
	return &MockSubscriberHandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, topic, subscriptionID, message
func (_m *MockSubscriberHandlerFunc) Execute(ctx context.Context, topic string, subscriptionID string, message []byte) error {
	ret := _m.Called(ctx, topic, subscriptionID, message)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, topic, subscriptionID, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriberHandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSubscriberHandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - subscriptionID string
//   - message []byte
func (_e *MockSubscriberHandlerFunc_Expecter) Execute(ctx interface{}, topic interface{}, subscriptionID interface{}, message interface{}) *MockSubscriberHandlerFunc_Execute_Call {
	return &MockSubscriberHandlerFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, topic, subscriptionID, message)}
}

func (_c *MockSubscriberHandlerFunc_Execute_Call) Run(run func(ctx context.Context, topic string, subscriptionID string, message []byte)) *MockSubscriberHandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockSubscriberHandlerFunc_Execute_Call) Return(_a0 error) *MockSubscriberHandlerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriberHandlerFunc_Execute_Call) RunAndReturn(run func(context.Context, string, string, []byte) error) *MockSubscriberHandlerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriberHandlerFunc creates a new instance of MockSubscriberHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriberHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriberHandlerFunc {
	mock := &MockSubscriberHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
