run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  go: "1.23"

output:
  # Formats:
  # - `colored-line-number`
  # - `line-number`
  # - `json`
  # - `colored-tab`
  # - `tab`
  # - `html`
  # - `checkstyle`
  # - `code-climate`
  # - `junit-xml`
  # - `github-actions`
  # - `teamcity`
  # - `sarif`
  formats:
    - format: tab
  print-issued-lines: true
  print-linter-name: true
  path-prefix: ""
  sort-results: false
  show-stats: true

linters-settings:
  cyclop:
    max-complexity: 20
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    default-signifies-exhaustive: true
  nolintlint:
    require-explanation: true
    require-specific: true
  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx
  gosec:
    excludes:
      - G115
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  lll:
    line-length: 110

linters:
  # disable-all: true
  # enable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - mnd
    - varnamelen
    - wrapcheck
    - wsl

issues:
  uniq-by-line: true
  exclude-dirs:
    - ".*/mocks"
    - ".*/mockz"
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"
  fix: true
