quiet: True
with-expecter: True
disable-version-string: True
packages:
  # dbops: skip, using github.com/DATA-DOG/go-sqlmock instead
  # task: skip, because i dont know the usecases yet
  # errs: skip, because errs does not have interfaces
  # http: skip, using net/http/httptest instead

  github.com/shandysiswandi/gostarter/pkg/clock:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/codec:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/config:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/emitter:
    interfaces:
      Emitter:
        config:
          filename: "mock_{{ .InterfaceName | snakecase }}.go"
          dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/logger:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/messaging:
    interfaces:
      Client:
        config:
          filename: "mock_{{ .InterfaceName | snakecase }}.go"
          dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/uid:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/validation:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: "{{ .InterfaceDir }}/mocker"
