quiet: True
with-expecter: True
disable-version-string: True
packages:
  # dbops: skip, using github.com/DATA-DOG/go-sqlmock instead
  # task: skip, because i don't know the useases yet
  # errs: skip, because errs does not have interfaces
  # http: skip, using net/http/httptest instead

  github.com/shandysiswandi/gostarter/pkg/clock:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      outpkg: "mocker"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/codec:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      outpkg: "mocker"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/config:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      outpkg: "mocker"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/emitter:
    interfaces:
      Emitter:
        config:
          filename: "mock_{{ .InterfaceName | snakecase }}.go"
          outpkg: "mocker"
          dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/hash:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      outpkg: "mocker"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/jwt:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      outpkg: "mocker"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/messaging:
    interfaces:
      Client:
        config:
          filename: "mock_{{ .InterfaceName | snakecase }}.go"
          outpkg: "mocker"
          dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/storage:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      outpkg: "mocker"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/uid:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      outpkg: "mocker"
      dir: "{{ .InterfaceDir }}/mocker"

  github.com/shandysiswandi/gostarter/pkg/validation:
    config:
      all: True
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      outpkg: "mocker"
      dir: "{{ .InterfaceDir }}/mocker"

  # MODULES
  github.com/shandysiswandi/gostarter/internal/auth:
    config:
      all: True
      recursive: True
      outpkg: "mockz"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/auth/internal/mockz

  github.com/shandysiswandi/gostarter/internal/payment:
    config:
      all: True
      recursive: True
      outpkg: "mockz"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/payment/internal/mockz

  github.com/shandysiswandi/gostarter/internal/user:
    config:
      all: True
      recursive: True
      outpkg: "mockz"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/user/internal/mockz

  github.com/shandysiswandi/gostarter/internal/todo:
    config:
      all: True
      recursive: True
      outpkg: "mockz"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/todo/internal/mockz
