log-level: "" # info, warn, debug, "" mean quiet
with-expecter: True
issue-845-fix: True
resolve-type-alias: False
disable-version-string: True
packages:
  # dbops: skip, using github.com/DATA-DOG/go-sqlmock instead
  # task: skip, because i don't know the useases yet
  # errs: skip, because errs does not have interfaces
  # http: skip, using net/http/httptest instead

  # MODULES
  github.com/shandysiswandi/gostarter/internal/auth:
    config:
      all: True
      recursive: True
      outpkg: "mockz"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/auth/internal/mockz

  # github.com/shandysiswandi/gostarter/internal/payment:
  #   config:
  #     all: True
  #     recursive: True
  #     outpkg: "mockz"
  #     filename: "mock_{{ .InterfaceName | snakecase }}.go"
  #     dir: internal/payment/internal/mockz

  # github.com/shandysiswandi/gostarter/internal/user:
  #   config:
  #     all: True
  #     recursive: True
  #     outpkg: "mockz"
  #     filename: "mock_{{ .InterfaceName | snakecase }}.go"
  #     dir: internal/user/internal/mockz

  # github.com/shandysiswandi/gostarter/internal/todo:
  #   config:
  #     all: True
  #     recursive: True
  #     outpkg: "mockz"
  #     filename: "mock_{{ .InterfaceName | snakecase }}.go"
  #     dir: internal/todo/internal/mockz
