quiet: True
with-expecter: True
disable-version-string: True
packages:
  github.com/shandysiswandi/gostarter/pkg/clock:
    config:
      all: True
      inpackage: True
      filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
      dir: "{{ .InterfaceDir }}"
  github.com/shandysiswandi/gostarter/pkg/codec:
    config:
      all: True
      inpackage: True
      filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
      dir: "{{ .InterfaceDir }}"
  github.com/shandysiswandi/gostarter/pkg/config:
    config:
      all: True
      inpackage: True
      filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
      dir: "{{ .InterfaceDir }}"
  github.com/shandysiswandi/gostarter/pkg/emitter:
    interfaces:
      Emitter:
        config:
          inpackage: True
          filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
          dir: "{{ .InterfaceDir }}"
      TimeProvider:
        config:
          inpackage: True
          filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
          dir: "{{ .InterfaceDir }}"
  # errs: skip, because errs does not have interfaces
  # http: skip, using net/http/httptest instead
  github.com/shandysiswandi/gostarter/pkg/logger:
    config:
      all: True
      inpackage: True
      filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
      dir: "{{ .InterfaceDir }}"
  github.com/shandysiswandi/gostarter/pkg/messaging:
    interfaces:
      Client:
        config:
          inpackage: True
          filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
          dir: "{{ .InterfaceDir }}"
  # persistence: skip, using github.com/DATA-DOG/go-sqlmock instead
  # task: skip, because i dont know the usecases yet
  github.com/shandysiswandi/gostarter/pkg/uid:
    config:
      all: True
      inpackage: True
      filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
      dir: "{{ .InterfaceDir }}"
  github.com/shandysiswandi/gostarter/pkg/validation:
    config:
      all: True
      inpackage: True
      filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
      dir: "{{ .InterfaceDir }}"
