services:
  app:
    image: gostarter
    pull_policy: missing
    build:
      context: .
    ports:
      - "8081:8081"
      - "8082:8082"
      - "50001:50001"
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./config/config.yaml:/config/config.yaml
    networks:
      - gostarter-network
    depends_on:
      redis:
        condition: service_healthy
      goose:
        condition: service_completed_successfully

  otelcol:
    image: otel/opentelemetry-collector:0.115.1
    pull_policy: missing
    ports:
      - 4317:4317
      - 4318:4318
      - 13133:13133 # health_check extension
    volumes:
      - ./config/otel-config.yaml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    networks:
      - gostarter-network

  goose:
    image: alpine
    pull_policy: missing
    volumes:
      - ./migrations:/migrations
    networks:
      - gostarter-network
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    entrypoint: >
      sh -c "
      apk add --no-cache curl && \
      curl -fsSL https://github.com/pressly/goose/releases/download/v3.23.0/goose_linux_x86_64 -o /goose && \
      chmod +x /goose && \

      /goose -dir /migrations/postgres fix && \
      /goose -dir /migrations/postgres postgres \"postgres://user:password@postgres:5432/gostarter?sslmode=disable\" up && \

      /goose -dir /migrations/mysql fix && \
      /goose -dir /migrations/mysql mysql \"user:password@tcp(mysql:3306)/gostarter?parseTime=true\" up
      "

  postgres:
    image: postgres:17-alpine
    pull_policy: missing
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gostarter-network
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: gostarter
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=gostarter"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0-debian
    pull_policy: missing
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gostarter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gostarter-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent -uuser -ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    pull_policy: missing
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gostarter-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mysql_data:
  redis_data:

networks:
  gostarter-network:
    driver: bridge
