services:
  app:
    image: gostarter
    build:
      context: .
    ports:
      - "8081:8081"
      - "8082:8082"
      - "50001:50001"
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./config/config.yaml:/config/config.yaml
    networks:
      - gostarter-network
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gostarter-network
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: gostarter
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=gostarter"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gostarter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gostarter-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent -uuser -ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gostarter-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mysql_data:
  redis_data:

networks:
  gostarter-network:
    driver: bridge
