// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/todo/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockFind is an autogenerated mock type for the Find type
type MockFind struct {
	mock.Mock
}

type MockFind_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFind) EXPECT() *MockFind_Expecter {
	return &MockFind_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockFind) Call(ctx context.Context, in domain.FindInput) (*domain.Todo, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.FindInput) (*domain.Todo, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.FindInput) *domain.Todo); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.FindInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFind_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockFind_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.FindInput
func (_e *MockFind_Expecter) Call(ctx interface{}, in interface{}) *MockFind_Call_Call {
	return &MockFind_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockFind_Call_Call) Run(run func(ctx context.Context, in domain.FindInput)) *MockFind_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.FindInput))
	})
	return _c
}

func (_c *MockFind_Call_Call) Return(_a0 *domain.Todo, _a1 error) *MockFind_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFind_Call_Call) RunAndReturn(run func(context.Context, domain.FindInput) (*domain.Todo, error)) *MockFind_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFind creates a new instance of MockFind. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFind(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFind {
	mock := &MockFind{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
