// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	usecase "github.com/shandysiswandi/gostarter/internal/todo/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockGetByID is an autogenerated mock type for the GetByID type
type MockGetByID struct {
	mock.Mock
}

type MockGetByID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetByID) EXPECT() *MockGetByID_Expecter {
	return &MockGetByID_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockGetByID) Execute(ctx context.Context, in usecase.GetByIDInput) (*usecase.GetByIDOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecase.GetByIDOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetByIDInput) (*usecase.GetByIDOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetByIDInput) *usecase.GetByIDOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.GetByIDOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.GetByIDInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetByID_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetByID_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.GetByIDInput
func (_e *MockGetByID_Expecter) Execute(ctx interface{}, in interface{}) *MockGetByID_Execute_Call {
	return &MockGetByID_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockGetByID_Execute_Call) Run(run func(ctx context.Context, in usecase.GetByIDInput)) *MockGetByID_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.GetByIDInput))
	})
	return _c
}

func (_c *MockGetByID_Execute_Call) Return(_a0 *usecase.GetByIDOutput, _a1 error) *MockGetByID_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetByID_Execute_Call) RunAndReturn(run func(context.Context, usecase.GetByIDInput) (*usecase.GetByIDOutput, error)) *MockGetByID_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetByID creates a new instance of MockGetByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetByID {
	mock := &MockGetByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
