// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	entity "github.com/shandysiswandi/gostarter/internal/todo/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockGetWithFilterStore is an autogenerated mock type for the GetWithFilterStore type
type MockGetWithFilterStore struct {
	mock.Mock
}

type MockGetWithFilterStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetWithFilterStore) EXPECT() *MockGetWithFilterStore_Expecter {
	return &MockGetWithFilterStore_Expecter{mock: &_m.Mock}
}

// GetWithFilter provides a mock function with given fields: ctx, filter
func (_m *MockGetWithFilterStore) GetWithFilter(ctx context.Context, filter map[string]string) ([]entity.Todo, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetWithFilter")
	}

	var r0 []entity.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) ([]entity.Todo, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) []entity.Todo); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetWithFilterStore_GetWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithFilter'
type MockGetWithFilterStore_GetWithFilter_Call struct {
	*mock.Call
}

// GetWithFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]string
func (_e *MockGetWithFilterStore_Expecter) GetWithFilter(ctx interface{}, filter interface{}) *MockGetWithFilterStore_GetWithFilter_Call {
	return &MockGetWithFilterStore_GetWithFilter_Call{Call: _e.mock.On("GetWithFilter", ctx, filter)}
}

func (_c *MockGetWithFilterStore_GetWithFilter_Call) Run(run func(ctx context.Context, filter map[string]string)) *MockGetWithFilterStore_GetWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]string))
	})
	return _c
}

func (_c *MockGetWithFilterStore_GetWithFilter_Call) Return(_a0 []entity.Todo, _a1 error) *MockGetWithFilterStore_GetWithFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetWithFilterStore_GetWithFilter_Call) RunAndReturn(run func(context.Context, map[string]string) ([]entity.Todo, error)) *MockGetWithFilterStore_GetWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetWithFilterStore creates a new instance of MockGetWithFilterStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetWithFilterStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetWithFilterStore {
	mock := &MockGetWithFilterStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
