// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	usecase "github.com/shandysiswandi/gostarter/internal/todo/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockGetWithFilter is an autogenerated mock type for the GetWithFilter type
type MockGetWithFilter struct {
	mock.Mock
}

type MockGetWithFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetWithFilter) EXPECT() *MockGetWithFilter_Expecter {
	return &MockGetWithFilter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockGetWithFilter) Execute(ctx context.Context, in usecase.GetWithFilterInput) (*usecase.GetWithFilterOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecase.GetWithFilterOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetWithFilterInput) (*usecase.GetWithFilterOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetWithFilterInput) *usecase.GetWithFilterOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.GetWithFilterOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.GetWithFilterInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetWithFilter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetWithFilter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.GetWithFilterInput
func (_e *MockGetWithFilter_Expecter) Execute(ctx interface{}, in interface{}) *MockGetWithFilter_Execute_Call {
	return &MockGetWithFilter_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockGetWithFilter_Execute_Call) Run(run func(ctx context.Context, in usecase.GetWithFilterInput)) *MockGetWithFilter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.GetWithFilterInput))
	})
	return _c
}

func (_c *MockGetWithFilter_Execute_Call) Return(_a0 *usecase.GetWithFilterOutput, _a1 error) *MockGetWithFilter_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetWithFilter_Execute_Call) RunAndReturn(run func(context.Context, usecase.GetWithFilterInput) (*usecase.GetWithFilterOutput, error)) *MockGetWithFilter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetWithFilter creates a new instance of MockGetWithFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetWithFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetWithFilter {
	mock := &MockGetWithFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
