// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	usecase "github.com/shandysiswandi/gostarter/internal/todo/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockDelete is an autogenerated mock type for the Delete type
type MockDelete struct {
	mock.Mock
}

type MockDelete_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDelete) EXPECT() *MockDelete_Expecter {
	return &MockDelete_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockDelete) Execute(ctx context.Context, in usecase.DeleteInput) (*usecase.DeleteOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecase.DeleteOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.DeleteInput) (*usecase.DeleteOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.DeleteInput) *usecase.DeleteOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.DeleteOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.DeleteInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDelete_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDelete_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.DeleteInput
func (_e *MockDelete_Expecter) Execute(ctx interface{}, in interface{}) *MockDelete_Execute_Call {
	return &MockDelete_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockDelete_Execute_Call) Run(run func(ctx context.Context, in usecase.DeleteInput)) *MockDelete_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.DeleteInput))
	})
	return _c
}

func (_c *MockDelete_Execute_Call) Return(_a0 *usecase.DeleteOutput, _a1 error) *MockDelete_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDelete_Execute_Call) RunAndReturn(run func(context.Context, usecase.DeleteInput) (*usecase.DeleteOutput, error)) *MockDelete_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDelete creates a new instance of MockDelete. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDelete(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDelete {
	mock := &MockDelete{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
