// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/todo/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateStatus is an autogenerated mock type for the UpdateStatus type
type MockUpdateStatus struct {
	mock.Mock
}

type MockUpdateStatus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateStatus) EXPECT() *MockUpdateStatus_Expecter {
	return &MockUpdateStatus_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockUpdateStatus) Execute(ctx context.Context, in domain.UpdateStatusInput) (*domain.UpdateStatusOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.UpdateStatusOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateStatusInput) (*domain.UpdateStatusOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateStatusInput) *domain.UpdateStatusOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UpdateStatusOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateStatusInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateStatus_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateStatus_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.UpdateStatusInput
func (_e *MockUpdateStatus_Expecter) Execute(ctx interface{}, in interface{}) *MockUpdateStatus_Execute_Call {
	return &MockUpdateStatus_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockUpdateStatus_Execute_Call) Run(run func(ctx context.Context, in domain.UpdateStatusInput)) *MockUpdateStatus_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UpdateStatusInput))
	})
	return _c
}

func (_c *MockUpdateStatus_Execute_Call) Return(_a0 *domain.UpdateStatusOutput, _a1 error) *MockUpdateStatus_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateStatus_Execute_Call) RunAndReturn(run func(context.Context, domain.UpdateStatusInput) (*domain.UpdateStatusOutput, error)) *MockUpdateStatus_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateStatus creates a new instance of MockUpdateStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateStatus {
	mock := &MockUpdateStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
