// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/todo/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateStore is an autogenerated mock type for the CreateStore type
type MockCreateStore struct {
	mock.Mock
}

type MockCreateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateStore) EXPECT() *MockCreateStore_Expecter {
	return &MockCreateStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockCreateStore) Create(ctx context.Context, in domain.Todo) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Todo) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCreateStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCreateStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.Todo
func (_e *MockCreateStore_Expecter) Create(ctx interface{}, in interface{}) *MockCreateStore_Create_Call {
	return &MockCreateStore_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockCreateStore_Create_Call) Run(run func(ctx context.Context, in domain.Todo)) *MockCreateStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Todo))
	})
	return _c
}

func (_c *MockCreateStore_Create_Call) Return(_a0 error) *MockCreateStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCreateStore_Create_Call) RunAndReturn(run func(context.Context, domain.Todo) error) *MockCreateStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateStore creates a new instance of MockCreateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateStore {
	mock := &MockCreateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
