// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/todo/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockDelete is an autogenerated mock type for the Delete type
type MockDelete struct {
	mock.Mock
}

type MockDelete_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDelete) EXPECT() *MockDelete_Expecter {
	return &MockDelete_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockDelete) Call(ctx context.Context, in domain.DeleteInput) (*domain.DeleteOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.DeleteOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.DeleteInput) (*domain.DeleteOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.DeleteInput) *domain.DeleteOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DeleteOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.DeleteInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDelete_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockDelete_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.DeleteInput
func (_e *MockDelete_Expecter) Call(ctx interface{}, in interface{}) *MockDelete_Call_Call {
	return &MockDelete_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockDelete_Call_Call) Run(run func(ctx context.Context, in domain.DeleteInput)) *MockDelete_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.DeleteInput))
	})
	return _c
}

func (_c *MockDelete_Call_Call) Return(_a0 *domain.DeleteOutput, _a1 error) *MockDelete_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDelete_Call_Call) RunAndReturn(run func(context.Context, domain.DeleteInput) (*domain.DeleteOutput, error)) *MockDelete_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDelete creates a new instance of MockDelete. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDelete(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDelete {
	mock := &MockDelete{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
