// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/user/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockProfileStore is an autogenerated mock type for the ProfileStore type
type MockProfileStore struct {
	mock.Mock
}

type MockProfileStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileStore) EXPECT() *MockProfileStore_Expecter {
	return &MockProfileStore_Expecter{mock: &_m.Mock}
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockProfileStore) FindUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProfileStore_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockProfileStore_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockProfileStore_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *MockProfileStore_FindUserByEmail_Call {
	return &MockProfileStore_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *MockProfileStore_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockProfileStore_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProfileStore_FindUserByEmail_Call) Return(_a0 *domain.User, _a1 error) *MockProfileStore_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProfileStore_FindUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockProfileStore_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileStore creates a new instance of MockProfileStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileStore {
	mock := &MockProfileStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
