// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/user/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockLogout is an autogenerated mock type for the Logout type
type MockLogout struct {
	mock.Mock
}

type MockLogout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogout) EXPECT() *MockLogout_Expecter {
	return &MockLogout_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockLogout) Call(ctx context.Context, in domain.LogoutInput) (*domain.LogoutOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.LogoutOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LogoutInput) (*domain.LogoutOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LogoutInput) *domain.LogoutOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LogoutOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LogoutInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogout_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockLogout_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.LogoutInput
func (_e *MockLogout_Expecter) Call(ctx interface{}, in interface{}) *MockLogout_Call_Call {
	return &MockLogout_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockLogout_Call_Call) Run(run func(ctx context.Context, in domain.LogoutInput)) *MockLogout_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.LogoutInput))
	})
	return _c
}

func (_c *MockLogout_Call_Call) Return(_a0 *domain.LogoutOutput, _a1 error) *MockLogout_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogout_Call_Call) RunAndReturn(run func(context.Context, domain.LogoutInput) (*domain.LogoutOutput, error)) *MockLogout_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogout creates a new instance of MockLogout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogout {
	mock := &MockLogout{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
