// Code generated by mockery. DO NOT EDIT.

package mockz

import mock "github.com/stretchr/testify/mock"

// MockGetImageStore is an autogenerated mock type for the GetImageStore type
type MockGetImageStore struct {
	mock.Mock
}

type MockGetImageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetImageStore) EXPECT() *MockGetImageStore_Expecter {
	return &MockGetImageStore_Expecter{mock: &_m.Mock}
}

// NewMockGetImageStore creates a new instance of MockGetImageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetImageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetImageStore {
	mock := &MockGetImageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
