// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/gallery/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockGetImage is an autogenerated mock type for the GetImage type
type MockGetImage struct {
	mock.Mock
}

type MockGetImage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetImage) EXPECT() *MockGetImage_Expecter {
	return &MockGetImage_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockGetImage) Call(ctx context.Context, in domain.GetImageInput) (*domain.GetImageOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.GetImageOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetImageInput) (*domain.GetImageOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetImageInput) *domain.GetImageOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetImageOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetImageInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetImage_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockGetImage_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.GetImageInput
func (_e *MockGetImage_Expecter) Call(ctx interface{}, in interface{}) *MockGetImage_Call_Call {
	return &MockGetImage_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockGetImage_Call_Call) Run(run func(ctx context.Context, in domain.GetImageInput)) *MockGetImage_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.GetImageInput))
	})
	return _c
}

func (_c *MockGetImage_Call_Call) Return(_a0 *domain.GetImageOutput, _a1 error) *MockGetImage_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetImage_Call_Call) RunAndReturn(run func(context.Context, domain.GetImageInput) (*domain.GetImageOutput, error)) *MockGetImage_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetImage creates a new instance of MockGetImage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetImage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetImage {
	mock := &MockGetImage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
