// Code generated by mockery. DO NOT EDIT.

package mockz

import mock "github.com/stretchr/testify/mock"

// MockUploadStore is an autogenerated mock type for the UploadStore type
type MockUploadStore struct {
	mock.Mock
}

type MockUploadStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadStore) EXPECT() *MockUploadStore_Expecter {
	return &MockUploadStore_Expecter{mock: &_m.Mock}
}

// NewMockUploadStore creates a new instance of MockUploadStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadStore {
	mock := &MockUploadStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
