// Code generated by mockery. DO NOT EDIT.

package uid

import mock "github.com/stretchr/testify/mock"

// MockStringID is an autogenerated mock type for the StringID type
type MockStringID struct {
	mock.Mock
}

type MockStringID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStringID) EXPECT() *MockStringID_Expecter {
	return &MockStringID_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields:
func (_m *MockStringID) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStringID_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockStringID_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockStringID_Expecter) Generate() *MockStringID_Generate_Call {
	return &MockStringID_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockStringID_Generate_Call) Run(run func()) *MockStringID_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStringID_Generate_Call) Return(_a0 string) *MockStringID_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStringID_Generate_Call) RunAndReturn(run func() string) *MockStringID_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStringID creates a new instance of MockStringID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStringID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStringID {
	mock := &MockStringID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
