// Code generated by mockery. DO NOT EDIT.

package mocker

import mock "github.com/stretchr/testify/mock"

// MockNumberID is an autogenerated mock type for the NumberID type
type MockNumberID struct {
	mock.Mock
}

type MockNumberID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNumberID) EXPECT() *MockNumberID_Expecter {
	return &MockNumberID_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields:
func (_m *MockNumberID) Generate() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockNumberID_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockNumberID_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockNumberID_Expecter) Generate() *MockNumberID_Generate_Call {
	return &MockNumberID_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockNumberID_Generate_Call) Run(run func()) *MockNumberID_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNumberID_Generate_Call) Return(_a0 uint64) *MockNumberID_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNumberID_Generate_Call) RunAndReturn(run func() uint64) *MockNumberID_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNumberID creates a new instance of MockNumberID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNumberID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNumberID {
	mock := &MockNumberID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
