# The query type, represents all of the entry points into our object graph
type Query {
  fetch(in: FetchInput): [Todo!]!
  find(id: String!): Todo
}

# The mutation type, represents all updates we can make to our data
type Mutation {
  create(in: CreateInput!): String!
  delete(id: String!): String!
  updateStatus(in: UpdateStatusInput!): UpdateStatusOutput!
  update(in: UpdateInput!): UpdateOutput!
}

# type ...........................

type Todo {
  id: String!
  title: String!
  description: String!
  status: Status!
}

enum Status {
  UNKNOWN
  INITIATE
  IN_PROGRESS
  DROP
  DONE
}

# inputs .........................

input FetchInput {
  id: String
  title: String
  description: String
  status: Status
}

input CreateInput {
  title: String!
  description: String!
}

input UpdateStatusInput {
  id: String!
  status: Status!
}

input UpdateInput {
  id: String!
  title: String!
  description: String!
  status: Status!
}

# response .......................

type UpdateStatusOutput {
  id: String!
  status: Status!
}

type UpdateOutput {
  id: String!
  title: String!
  description: String!
  status: Status!
}
