server.address.http: localhost:8080
server.address.grpc: localhost:50000

database.driver: mysql
database.user:
database.pass:
database.host: localhost
database.port: 3306
database.name:
database.max.open: 10
database.max.idle: 10
database.max.lifetime: 5

redis.addr: localhost:6379

feature.flag.graphql.playground: true
