server.address.http: localhost:8080
server.address.gql: localhost:8181
server.address.grpc: localhost:50000

telemetry.name: gostarter
telemetry.otlp.grpc.address: localhost:4317
telemetry.otlp.http.address: localhost:4318

tz: "Asia/Jakarta"

pubsub.project.id: "google project id"

database.driver: mysql
database.user:
database.pass:
database.host: localhost
database.port: 3306
database.name:
database.max.open: 10
database.max.idle: 10
database.max.lifetime: 5

redis.addr: localhost:6379

jwt.public.key: base64ofpublickey
jwt.private.key: base64ofprivatekey
jwt.secret: secret
jwt.algorithm: asymmetric # asymmetric or symmetric

hash.sha256.secret: secret

init.flag.messaging: false

feature.flag.graphql.playground: false
feature.flag.todo.job: false

module.flag.auth: true
module.flag.rbac: true
module.flag.user: true
module.flag.todo: true
module.flag.payment: true
