server.address.http: localhost:8080
server.address.grpc: localhost:50000

telemetry.name: gostarter
telemetry.jaeger.address: localhost:4318

tz: "Asia/Jakarta"

database.driver: mysql
database.user:
database.pass:
database.host: localhost
database.port: 3306
database.name:
database.max.open: 10
database.max.idle: 10
database.max.lifetime: 5

redis.addr: localhost:6379

jwt.public.key: base64ofpublickey
jwt.private.key: base64ofprivatekey
jwt.hash.secret: secret

feature.flag.graphql.playground: true

module.flag.auth: true
module.flag.gallery: true
module.flag.region: true
module.flag.shortly: true
module.flag.todo: true
