// Package uid provides interfaces and implementations for generating unique identifiers (UIDs).
package uid

import "github.com/google/uuid"

// UUIDString is an implementation of UIDString that uses UUID for generating unique string-based UIDs.
//
// UUIDs (Universally Unique Identifiers) are standardized 128-bit values represented as strings. This implementation
// uses the Google UUID library to generate version 4 UUIDs, which are randomly generated and have a low probability
// of collision.
//
// The UUIDs generated by this implementation follow the UUID v4 specification and are represented as 36-character
// strings including hyphens.
type UUIDString struct{}

// NewUUIDString creates and returns a new instance of UUIDString.
//
// This function provides a convenient way to instantiate a UUIDString generator, which can then be used to generate
// unique UUID strings. There are no configuration options for this generator; it will always produce version 4 UUIDs.
func NewUUIDString() *UUIDString {
	return &UUIDString{}
}

// Generate generates a unique identifier as a string using UUID.
//
// The generated UUID is a 36-character string (including hyphens) that represents a 128-bit value. UUIDs are
// universally unique, making them suitable for a wide range of applications where unique identifiers are required.
func (u *UUIDString) Generate() string {
	return uuid.NewString()
}
