// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/shortly/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSet is an autogenerated mock type for the Set type
type MockSet struct {
	mock.Mock
}

type MockSet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSet) EXPECT() *MockSet_Expecter {
	return &MockSet_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockSet) Call(ctx context.Context, in domain.SetInput) (*domain.SetOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.SetOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SetInput) (*domain.SetOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SetInput) *domain.SetOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SetOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SetInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSet_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockSet_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.SetInput
func (_e *MockSet_Expecter) Call(ctx interface{}, in interface{}) *MockSet_Call_Call {
	return &MockSet_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockSet_Call_Call) Run(run func(ctx context.Context, in domain.SetInput)) *MockSet_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SetInput))
	})
	return _c
}

func (_c *MockSet_Call_Call) Return(_a0 *domain.SetOutput, _a1 error) *MockSet_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSet_Call_Call) RunAndReturn(run func(context.Context, domain.SetInput) (*domain.SetOutput, error)) *MockSet_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSet creates a new instance of MockSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSet {
	mock := &MockSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
