// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/shortly/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockGetStore is an autogenerated mock type for the GetStore type
type MockGetStore struct {
	mock.Mock
}

type MockGetStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetStore) EXPECT() *MockGetStore_Expecter {
	return &MockGetStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockGetStore) Get(ctx context.Context, key string) (*domain.Short, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Short
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Short, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Short); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Short)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGetStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockGetStore_Expecter) Get(ctx interface{}, key interface{}) *MockGetStore_Get_Call {
	return &MockGetStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockGetStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockGetStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetStore_Get_Call) Return(_a0 *domain.Short, _a1 error) *MockGetStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetStore_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.Short, error)) *MockGetStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetStore creates a new instance of MockGetStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetStore {
	mock := &MockGetStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
