// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/shortly/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockGet is an autogenerated mock type for the Get type
type MockGet struct {
	mock.Mock
}

type MockGet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGet) EXPECT() *MockGet_Expecter {
	return &MockGet_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockGet) Call(ctx context.Context, in domain.GetInput) (*domain.GetOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.GetOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetInput) (*domain.GetOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetInput) *domain.GetOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGet_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockGet_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.GetInput
func (_e *MockGet_Expecter) Call(ctx interface{}, in interface{}) *MockGet_Call_Call {
	return &MockGet_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockGet_Call_Call) Run(run func(ctx context.Context, in domain.GetInput)) *MockGet_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.GetInput))
	})
	return _c
}

func (_c *MockGet_Call_Call) Return(_a0 *domain.GetOutput, _a1 error) *MockGet_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGet_Call_Call) RunAndReturn(run func(context.Context, domain.GetInput) (*domain.GetOutput, error)) *MockGet_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGet creates a new instance of MockGet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGet {
	mock := &MockGet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
