// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/shortly/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSetStore is an autogenerated mock type for the SetStore type
type MockSetStore struct {
	mock.Mock
}

type MockSetStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSetStore) EXPECT() *MockSetStore_Expecter {
	return &MockSetStore_Expecter{mock: &_m.Mock}
}

// Set provides a mock function with given fields: ctx, value
func (_m *MockSetStore) Set(ctx context.Context, value domain.Short) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Short) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSetStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSetStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - value domain.Short
func (_e *MockSetStore_Expecter) Set(ctx interface{}, value interface{}) *MockSetStore_Set_Call {
	return &MockSetStore_Set_Call{Call: _e.mock.On("Set", ctx, value)}
}

func (_c *MockSetStore_Set_Call) Run(run func(ctx context.Context, value domain.Short)) *MockSetStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Short))
	})
	return _c
}

func (_c *MockSetStore_Set_Call) Return(_a0 error) *MockSetStore_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSetStore_Set_Call) RunAndReturn(run func(context.Context, domain.Short) error) *MockSetStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSetStore creates a new instance of MockSetStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSetStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSetStore {
	mock := &MockSetStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
