// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/payment/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentTopup is an autogenerated mock type for the PaymentTopup type
type MockPaymentTopup struct {
	mock.Mock
}

type MockPaymentTopup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentTopup) EXPECT() *MockPaymentTopup_Expecter {
	return &MockPaymentTopup_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockPaymentTopup) Call(ctx context.Context, in domain.PaymentTopupInput) (*domain.PaymentTopupOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.PaymentTopupOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentTopupInput) (*domain.PaymentTopupOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentTopupInput) *domain.PaymentTopupOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentTopupOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaymentTopupInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentTopup_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockPaymentTopup_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.PaymentTopupInput
func (_e *MockPaymentTopup_Expecter) Call(ctx interface{}, in interface{}) *MockPaymentTopup_Call_Call {
	return &MockPaymentTopup_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockPaymentTopup_Call_Call) Run(run func(ctx context.Context, in domain.PaymentTopupInput)) *MockPaymentTopup_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PaymentTopupInput))
	})
	return _c
}

func (_c *MockPaymentTopup_Call_Call) Return(_a0 *domain.PaymentTopupOutput, _a1 error) *MockPaymentTopup_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentTopup_Call_Call) RunAndReturn(run func(context.Context, domain.PaymentTopupInput) (*domain.PaymentTopupOutput, error)) *MockPaymentTopup_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentTopup creates a new instance of MockPaymentTopup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentTopup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentTopup {
	mock := &MockPaymentTopup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
