// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRefreshToken is an autogenerated mock type for the RefreshToken type
type MockRefreshToken struct {
	mock.Mock
}

type MockRefreshToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshToken) EXPECT() *MockRefreshToken_Expecter {
	return &MockRefreshToken_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockRefreshToken) Call(ctx context.Context, in domain.RefreshTokenInput) (*domain.RefreshTokenOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.RefreshTokenOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RefreshTokenInput) (*domain.RefreshTokenOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RefreshTokenInput) *domain.RefreshTokenOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshTokenOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RefreshTokenInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshToken_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockRefreshToken_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.RefreshTokenInput
func (_e *MockRefreshToken_Expecter) Call(ctx interface{}, in interface{}) *MockRefreshToken_Call_Call {
	return &MockRefreshToken_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockRefreshToken_Call_Call) Run(run func(ctx context.Context, in domain.RefreshTokenInput)) *MockRefreshToken_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RefreshTokenInput))
	})
	return _c
}

func (_c *MockRefreshToken_Call_Call) Return(_a0 *domain.RefreshTokenOutput, _a1 error) *MockRefreshToken_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshToken_Call_Call) RunAndReturn(run func(context.Context, domain.RefreshTokenInput) (*domain.RefreshTokenOutput, error)) *MockRefreshToken_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshToken creates a new instance of MockRefreshToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshToken {
	mock := &MockRefreshToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
