// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockForgotPassword is an autogenerated mock type for the ForgotPassword type
type MockForgotPassword struct {
	mock.Mock
}

type MockForgotPassword_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForgotPassword) EXPECT() *MockForgotPassword_Expecter {
	return &MockForgotPassword_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockForgotPassword) Call(ctx context.Context, in domain.ForgotPasswordInput) (*domain.ForgotPasswordOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.ForgotPasswordOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ForgotPasswordInput) (*domain.ForgotPasswordOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ForgotPasswordInput) *domain.ForgotPasswordOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ForgotPasswordOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ForgotPasswordInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockForgotPassword_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockForgotPassword_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.ForgotPasswordInput
func (_e *MockForgotPassword_Expecter) Call(ctx interface{}, in interface{}) *MockForgotPassword_Call_Call {
	return &MockForgotPassword_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockForgotPassword_Call_Call) Run(run func(ctx context.Context, in domain.ForgotPasswordInput)) *MockForgotPassword_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ForgotPasswordInput))
	})
	return _c
}

func (_c *MockForgotPassword_Call_Call) Return(_a0 *domain.ForgotPasswordOutput, _a1 error) *MockForgotPassword_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForgotPassword_Call_Call) RunAndReturn(run func(context.Context, domain.ForgotPasswordInput) (*domain.ForgotPasswordOutput, error)) *MockForgotPassword_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockForgotPassword creates a new instance of MockForgotPassword. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForgotPassword(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForgotPassword {
	mock := &MockForgotPassword{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
