// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRefreshTokenStore is an autogenerated mock type for the RefreshTokenStore type
type MockRefreshTokenStore struct {
	mock.Mock
}

type MockRefreshTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStore_Expecter {
	return &MockRefreshTokenStore_Expecter{mock: &_m.Mock}
}

// TokenByRefresh provides a mock function with given fields: ctx, ref
func (_m *MockRefreshTokenStore) TokenByRefresh(ctx context.Context, ref string) (*domain.Token, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for TokenByRefresh")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Token, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Token); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenStore_TokenByRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenByRefresh'
type MockRefreshTokenStore_TokenByRefresh_Call struct {
	*mock.Call
}

// TokenByRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *MockRefreshTokenStore_Expecter) TokenByRefresh(ctx interface{}, ref interface{}) *MockRefreshTokenStore_TokenByRefresh_Call {
	return &MockRefreshTokenStore_TokenByRefresh_Call{Call: _e.mock.On("TokenByRefresh", ctx, ref)}
}

func (_c *MockRefreshTokenStore_TokenByRefresh_Call) Run(run func(ctx context.Context, ref string)) *MockRefreshTokenStore_TokenByRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenStore_TokenByRefresh_Call) Return(_a0 *domain.Token, _a1 error) *MockRefreshTokenStore_TokenByRefresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenStore_TokenByRefresh_Call) RunAndReturn(run func(context.Context, string) (*domain.Token, error)) *MockRefreshTokenStore_TokenByRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// TokenSave provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenStore) TokenSave(ctx context.Context, token domain.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for TokenSave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenStore_TokenSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenSave'
type MockRefreshTokenStore_TokenSave_Call struct {
	*mock.Call
}

// TokenSave is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.Token
func (_e *MockRefreshTokenStore_Expecter) TokenSave(ctx interface{}, token interface{}) *MockRefreshTokenStore_TokenSave_Call {
	return &MockRefreshTokenStore_TokenSave_Call{Call: _e.mock.On("TokenSave", ctx, token)}
}

func (_c *MockRefreshTokenStore_TokenSave_Call) Run(run func(ctx context.Context, token domain.Token)) *MockRefreshTokenStore_TokenSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Token))
	})
	return _c
}

func (_c *MockRefreshTokenStore_TokenSave_Call) Return(_a0 error) *MockRefreshTokenStore_TokenSave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenStore_TokenSave_Call) RunAndReturn(run func(context.Context, domain.Token) error) *MockRefreshTokenStore_TokenSave_Call {
	_c.Call.Return(run)
	return _c
}

// TokenUpdate provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenStore) TokenUpdate(ctx context.Context, token domain.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for TokenUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenStore_TokenUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenUpdate'
type MockRefreshTokenStore_TokenUpdate_Call struct {
	*mock.Call
}

// TokenUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.Token
func (_e *MockRefreshTokenStore_Expecter) TokenUpdate(ctx interface{}, token interface{}) *MockRefreshTokenStore_TokenUpdate_Call {
	return &MockRefreshTokenStore_TokenUpdate_Call{Call: _e.mock.On("TokenUpdate", ctx, token)}
}

func (_c *MockRefreshTokenStore_TokenUpdate_Call) Run(run func(ctx context.Context, token domain.Token)) *MockRefreshTokenStore_TokenUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Token))
	})
	return _c
}

func (_c *MockRefreshTokenStore_TokenUpdate_Call) Return(_a0 error) *MockRefreshTokenStore_TokenUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenStore_TokenUpdate_Call) RunAndReturn(run func(context.Context, domain.Token) error) *MockRefreshTokenStore_TokenUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenStore creates a new instance of MockRefreshTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
