// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockResetPassword is an autogenerated mock type for the ResetPassword type
type MockResetPassword struct {
	mock.Mock
}

type MockResetPassword_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResetPassword) EXPECT() *MockResetPassword_Expecter {
	return &MockResetPassword_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockResetPassword) Call(ctx context.Context, in domain.ResetPasswordInput) (*domain.ResetPasswordOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.ResetPasswordOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ResetPasswordInput) (*domain.ResetPasswordOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ResetPasswordInput) *domain.ResetPasswordOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ResetPasswordOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ResetPasswordInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResetPassword_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockResetPassword_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.ResetPasswordInput
func (_e *MockResetPassword_Expecter) Call(ctx interface{}, in interface{}) *MockResetPassword_Call_Call {
	return &MockResetPassword_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockResetPassword_Call_Call) Run(run func(ctx context.Context, in domain.ResetPasswordInput)) *MockResetPassword_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ResetPasswordInput))
	})
	return _c
}

func (_c *MockResetPassword_Call_Call) Return(_a0 *domain.ResetPasswordOutput, _a1 error) *MockResetPassword_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResetPassword_Call_Call) RunAndReturn(run func(context.Context, domain.ResetPasswordInput) (*domain.ResetPasswordOutput, error)) *MockResetPassword_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResetPassword creates a new instance of MockResetPassword. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResetPassword(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResetPassword {
	mock := &MockResetPassword{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
