// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockLoginStore is an autogenerated mock type for the LoginStore type
type MockLoginStore struct {
	mock.Mock
}

type MockLoginStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginStore) EXPECT() *MockLoginStore_Expecter {
	return &MockLoginStore_Expecter{mock: &_m.Mock}
}

// FindTokenByUserID provides a mock function with given fields: ctx, uid
func (_m *MockLoginStore) FindTokenByUserID(ctx context.Context, uid uint64) (*domain.Token, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for FindTokenByUserID")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.Token, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.Token); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginStore_FindTokenByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTokenByUserID'
type MockLoginStore_FindTokenByUserID_Call struct {
	*mock.Call
}

// FindTokenByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uint64
func (_e *MockLoginStore_Expecter) FindTokenByUserID(ctx interface{}, uid interface{}) *MockLoginStore_FindTokenByUserID_Call {
	return &MockLoginStore_FindTokenByUserID_Call{Call: _e.mock.On("FindTokenByUserID", ctx, uid)}
}

func (_c *MockLoginStore_FindTokenByUserID_Call) Run(run func(ctx context.Context, uid uint64)) *MockLoginStore_FindTokenByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockLoginStore_FindTokenByUserID_Call) Return(_a0 *domain.Token, _a1 error) *MockLoginStore_FindTokenByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginStore_FindTokenByUserID_Call) RunAndReturn(run func(context.Context, uint64) (*domain.Token, error)) *MockLoginStore_FindTokenByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockLoginStore) FindUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginStore_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockLoginStore_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockLoginStore_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *MockLoginStore_FindUserByEmail_Call {
	return &MockLoginStore_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *MockLoginStore_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockLoginStore_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLoginStore_FindUserByEmail_Call) Return(_a0 *domain.User, _a1 error) *MockLoginStore_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginStore_FindUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockLoginStore_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function with given fields: ctx, token
func (_m *MockLoginStore) SaveToken(ctx context.Context, token domain.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginStore_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type MockLoginStore_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.Token
func (_e *MockLoginStore_Expecter) SaveToken(ctx interface{}, token interface{}) *MockLoginStore_SaveToken_Call {
	return &MockLoginStore_SaveToken_Call{Call: _e.mock.On("SaveToken", ctx, token)}
}

func (_c *MockLoginStore_SaveToken_Call) Run(run func(ctx context.Context, token domain.Token)) *MockLoginStore_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Token))
	})
	return _c
}

func (_c *MockLoginStore_SaveToken_Call) Return(_a0 error) *MockLoginStore_SaveToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoginStore_SaveToken_Call) RunAndReturn(run func(context.Context, domain.Token) error) *MockLoginStore_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginStore creates a new instance of MockLoginStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginStore {
	mock := &MockLoginStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
