// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockVerify is an autogenerated mock type for the Verify type
type MockVerify struct {
	mock.Mock
}

type MockVerify_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerify) EXPECT() *MockVerify_Expecter {
	return &MockVerify_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockVerify) Call(ctx context.Context, in domain.VerifyInput) (*domain.VerifyOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.VerifyOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.VerifyInput) (*domain.VerifyOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.VerifyInput) *domain.VerifyOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VerifyOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.VerifyInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerify_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockVerify_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.VerifyInput
func (_e *MockVerify_Expecter) Call(ctx interface{}, in interface{}) *MockVerify_Call_Call {
	return &MockVerify_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockVerify_Call_Call) Run(run func(ctx context.Context, in domain.VerifyInput)) *MockVerify_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.VerifyInput))
	})
	return _c
}

func (_c *MockVerify_Call_Call) Return(_a0 *domain.VerifyOutput, _a1 error) *MockVerify_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerify_Call_Call) RunAndReturn(run func(context.Context, domain.VerifyInput) (*domain.VerifyOutput, error)) *MockVerify_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerify creates a new instance of MockVerify. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerify(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerify {
	mock := &MockVerify{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
