// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRefreshTokenStore is an autogenerated mock type for the RefreshTokenStore type
type MockRefreshTokenStore struct {
	mock.Mock
}

type MockRefreshTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStore_Expecter {
	return &MockRefreshTokenStore_Expecter{mock: &_m.Mock}
}

// FindTokenByRefresh provides a mock function with given fields: ctx, ref
func (_m *MockRefreshTokenStore) FindTokenByRefresh(ctx context.Context, ref string) (*domain.Token, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for FindTokenByRefresh")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Token, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Token); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenStore_FindTokenByRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTokenByRefresh'
type MockRefreshTokenStore_FindTokenByRefresh_Call struct {
	*mock.Call
}

// FindTokenByRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *MockRefreshTokenStore_Expecter) FindTokenByRefresh(ctx interface{}, ref interface{}) *MockRefreshTokenStore_FindTokenByRefresh_Call {
	return &MockRefreshTokenStore_FindTokenByRefresh_Call{Call: _e.mock.On("FindTokenByRefresh", ctx, ref)}
}

func (_c *MockRefreshTokenStore_FindTokenByRefresh_Call) Run(run func(ctx context.Context, ref string)) *MockRefreshTokenStore_FindTokenByRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenStore_FindTokenByRefresh_Call) Return(_a0 *domain.Token, _a1 error) *MockRefreshTokenStore_FindTokenByRefresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenStore_FindTokenByRefresh_Call) RunAndReturn(run func(context.Context, string) (*domain.Token, error)) *MockRefreshTokenStore_FindTokenByRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenStore) SaveToken(ctx context.Context, token domain.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenStore_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type MockRefreshTokenStore_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.Token
func (_e *MockRefreshTokenStore_Expecter) SaveToken(ctx interface{}, token interface{}) *MockRefreshTokenStore_SaveToken_Call {
	return &MockRefreshTokenStore_SaveToken_Call{Call: _e.mock.On("SaveToken", ctx, token)}
}

func (_c *MockRefreshTokenStore_SaveToken_Call) Run(run func(ctx context.Context, token domain.Token)) *MockRefreshTokenStore_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Token))
	})
	return _c
}

func (_c *MockRefreshTokenStore_SaveToken_Call) Return(_a0 error) *MockRefreshTokenStore_SaveToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenStore_SaveToken_Call) RunAndReturn(run func(context.Context, domain.Token) error) *MockRefreshTokenStore_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateToken provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenStore) UpdateToken(ctx context.Context, token domain.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdateToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenStore_UpdateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateToken'
type MockRefreshTokenStore_UpdateToken_Call struct {
	*mock.Call
}

// UpdateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.Token
func (_e *MockRefreshTokenStore_Expecter) UpdateToken(ctx interface{}, token interface{}) *MockRefreshTokenStore_UpdateToken_Call {
	return &MockRefreshTokenStore_UpdateToken_Call{Call: _e.mock.On("UpdateToken", ctx, token)}
}

func (_c *MockRefreshTokenStore_UpdateToken_Call) Run(run func(ctx context.Context, token domain.Token)) *MockRefreshTokenStore_UpdateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Token))
	})
	return _c
}

func (_c *MockRefreshTokenStore_UpdateToken_Call) Return(_a0 error) *MockRefreshTokenStore_UpdateToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenStore_UpdateToken_Call) RunAndReturn(run func(context.Context, domain.Token) error) *MockRefreshTokenStore_UpdateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenStore creates a new instance of MockRefreshTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
