// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRegisterStore is an autogenerated mock type for the RegisterStore type
type MockRegisterStore struct {
	mock.Mock
}

type MockRegisterStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterStore) EXPECT() *MockRegisterStore_Expecter {
	return &MockRegisterStore_Expecter{mock: &_m.Mock}
}

// AccountSave provides a mock function with given fields: ctx, user
func (_m *MockRegisterStore) AccountSave(ctx context.Context, user domain.Account) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AccountSave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegisterStore_AccountSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountSave'
type MockRegisterStore_AccountSave_Call struct {
	*mock.Call
}

// AccountSave is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.Account
func (_e *MockRegisterStore_Expecter) AccountSave(ctx interface{}, user interface{}) *MockRegisterStore_AccountSave_Call {
	return &MockRegisterStore_AccountSave_Call{Call: _e.mock.On("AccountSave", ctx, user)}
}

func (_c *MockRegisterStore_AccountSave_Call) Run(run func(ctx context.Context, user domain.Account)) *MockRegisterStore_AccountSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Account))
	})
	return _c
}

func (_c *MockRegisterStore_AccountSave_Call) Return(_a0 error) *MockRegisterStore_AccountSave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegisterStore_AccountSave_Call) RunAndReturn(run func(context.Context, domain.Account) error) *MockRegisterStore_AccountSave_Call {
	_c.Call.Return(run)
	return _c
}

// UserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRegisterStore) UserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegisterStore_UserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByEmail'
type MockRegisterStore_UserByEmail_Call struct {
	*mock.Call
}

// UserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRegisterStore_Expecter) UserByEmail(ctx interface{}, email interface{}) *MockRegisterStore_UserByEmail_Call {
	return &MockRegisterStore_UserByEmail_Call{Call: _e.mock.On("UserByEmail", ctx, email)}
}

func (_c *MockRegisterStore_UserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRegisterStore_UserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegisterStore_UserByEmail_Call) Return(_a0 *domain.User, _a1 error) *MockRegisterStore_UserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegisterStore_UserByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockRegisterStore_UserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserSave provides a mock function with given fields: ctx, user
func (_m *MockRegisterStore) UserSave(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UserSave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegisterStore_UserSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserSave'
type MockRegisterStore_UserSave_Call struct {
	*mock.Call
}

// UserSave is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockRegisterStore_Expecter) UserSave(ctx interface{}, user interface{}) *MockRegisterStore_UserSave_Call {
	return &MockRegisterStore_UserSave_Call{Call: _e.mock.On("UserSave", ctx, user)}
}

func (_c *MockRegisterStore_UserSave_Call) Run(run func(ctx context.Context, user domain.User)) *MockRegisterStore_UserSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockRegisterStore_UserSave_Call) Return(_a0 error) *MockRegisterStore_UserSave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegisterStore_UserSave_Call) RunAndReturn(run func(context.Context, domain.User) error) *MockRegisterStore_UserSave_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegisterStore creates a new instance of MockRegisterStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterStore {
	mock := &MockRegisterStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
