// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRegisterStore is an autogenerated mock type for the RegisterStore type
type MockRegisterStore struct {
	mock.Mock
}

type MockRegisterStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterStore) EXPECT() *MockRegisterStore_Expecter {
	return &MockRegisterStore_Expecter{mock: &_m.Mock}
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRegisterStore) FindUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegisterStore_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockRegisterStore_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRegisterStore_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *MockRegisterStore_FindUserByEmail_Call {
	return &MockRegisterStore_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *MockRegisterStore_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRegisterStore_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegisterStore_FindUserByEmail_Call) Return(_a0 *domain.User, _a1 error) *MockRegisterStore_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegisterStore_FindUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockRegisterStore_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAccount provides a mock function with given fields: ctx, user
func (_m *MockRegisterStore) SaveAccount(ctx context.Context, user domain.Account) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegisterStore_SaveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAccount'
type MockRegisterStore_SaveAccount_Call struct {
	*mock.Call
}

// SaveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.Account
func (_e *MockRegisterStore_Expecter) SaveAccount(ctx interface{}, user interface{}) *MockRegisterStore_SaveAccount_Call {
	return &MockRegisterStore_SaveAccount_Call{Call: _e.mock.On("SaveAccount", ctx, user)}
}

func (_c *MockRegisterStore_SaveAccount_Call) Run(run func(ctx context.Context, user domain.Account)) *MockRegisterStore_SaveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Account))
	})
	return _c
}

func (_c *MockRegisterStore_SaveAccount_Call) Return(_a0 error) *MockRegisterStore_SaveAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegisterStore_SaveAccount_Call) RunAndReturn(run func(context.Context, domain.Account) error) *MockRegisterStore_SaveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function with given fields: ctx, user
func (_m *MockRegisterStore) SaveUser(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegisterStore_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockRegisterStore_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockRegisterStore_Expecter) SaveUser(ctx interface{}, user interface{}) *MockRegisterStore_SaveUser_Call {
	return &MockRegisterStore_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, user)}
}

func (_c *MockRegisterStore_SaveUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockRegisterStore_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockRegisterStore_SaveUser_Call) Return(_a0 error) *MockRegisterStore_SaveUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegisterStore_SaveUser_Call) RunAndReturn(run func(context.Context, domain.User) error) *MockRegisterStore_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegisterStore creates a new instance of MockRegisterStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterStore {
	mock := &MockRegisterStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
