// Code generated by mockery. DO NOT EDIT.

package mockz

import (
	context "context"

	domain "github.com/shandysiswandi/gostarter/internal/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRegister is an autogenerated mock type for the Register type
type MockRegister struct {
	mock.Mock
}

type MockRegister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegister) EXPECT() *MockRegister_Expecter {
	return &MockRegister_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, in
func (_m *MockRegister) Call(ctx context.Context, in domain.RegisterInput) (*domain.RegisterOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *domain.RegisterOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegisterInput) (*domain.RegisterOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegisterInput) *domain.RegisterOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RegisterOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RegisterInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegister_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockRegister_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.RegisterInput
func (_e *MockRegister_Expecter) Call(ctx interface{}, in interface{}) *MockRegister_Call_Call {
	return &MockRegister_Call_Call{Call: _e.mock.On("Call", ctx, in)}
}

func (_c *MockRegister_Call_Call) Run(run func(ctx context.Context, in domain.RegisterInput)) *MockRegister_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RegisterInput))
	})
	return _c
}

func (_c *MockRegister_Call_Call) Return(_a0 *domain.RegisterOutput, _a1 error) *MockRegister_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegister_Call_Call) RunAndReturn(run func(context.Context, domain.RegisterInput) (*domain.RegisterOutput, error)) *MockRegister_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegister creates a new instance of MockRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegister {
	mock := &MockRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
